name: Build and Analyze with SonarQube

on:
    pull_request:
        branches:
            - develop
            - master
            - release
    push:
        branches:
            - develop
            - master
            - release

jobs:
    build:
        name: Build and SonarQube Analysis
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # Ensure full history for SonarQube analysis

            # Set up Docker Build and analyze with SonarQube
            - name: Build Docker image
              run: |
                  docker build -t react-frontend-app .

            # Run SonarQube analysis inside the Docker container
            - name: SonarQube Scan
              run: |
                  docker run --rm \
                    -v $(pwd):/app \
                    -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
                    -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
                    sonarsource/sonar-scanner-cli:latest \
                    sonar-scanner -Dsonar.projectKey=my-react-app -Dsonar.sources=src -Dsonar.tests=src -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report/index.html

            # (Optional) Run additional steps like tests, deployments, etc.
            # - name: Deploy to server
            #   run: ...
